- .circleci/config.yml
- .gitmodules
- LICENSE
- build.gradle
- gradle.properties
- gradle/documentation.gradle
- gradle/wrapper/gradle-wrapper.properties
- miniapp/build.gradle
- miniapp/detekt-baseline.xml
- miniapp/src/test/java/com/rakuten/mobile/miniapp/download/DownloadBaseTest.kt
- testapp/build.gradle
This PR include changes to create the code infrastructure (static code analysis, documentation, CI, setup for releasing versions).
the publishing part and fixing detekt reported issues is to follow in the next PR
> add code infrastructure to the project

- build.gradle
- gradle.properties
- miniapp/build.gradle
- miniapp/src/main/java/com/rakuten/mobile/miniapp/download/data/response/ManifestResponse.kt
- miniapp/src/test/java/com/rakuten/mobile/miniapp/platform/MiniAppPlatformImplTest.kt
- settings.gradle
- testapp/build.gradle
This PR is focused on getting the publishing support added to the repository (at the same time cleans up some space in gradle properties).
Fixes for detekt issues (e.g. project wide indentation etc.) are to follow in the next PR.
> add publishing support

- build.gradle
move scmVersion block into allprojects to fix correct version embedding into artifacts
> make versioning plugin to execute for all projects

- .circleci/config.yml
- testapp/build.gradle
Also changed the versionCode and versionName for the test app because they were not getting set correctly. It might be nice if we could automatically increment the versionCode on CI, but it is not necessary at this time.
> ci: Deploy Test App to App Center on merge to master branch

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/DownloadApi.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/DownloadApiSpec.kt
Note: The consideration for `@Streaming` has been kept as a TODO
> feat: implement download api

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/FileWriter.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageTest.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListViewModel.kt
- remove invocation to obtain view in the sample app
- update the path scheme for file saving and fix file saving issue
- update the WebView loading based on the updated scheme
- update the public API interface
Please note that this PR is mostly oriented on migrating the implementation.
> Migrate useful stuff from poc branch

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
Please note: Some of this is based on the recent integration with backend and the issues observed at that time.
> add few validations and error case handling

- miniapp/src/main/AndroidManifest.xml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppView.kt
Remove unnecessary webview settings.
Add http net setting following [this](https://support.google.com/faqs/answer/7668153).
> update webview setting

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Added Issue templates (bug and feature), contribution guide w/ commit message guidelines, and pull request template.
> Add github templates (.github files)

- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputActivity.kt
- testapp/src/main/res/layout/mini_app_input_activity.xml
- testapp/src/main/res/values/strings.xml
Working on sample app.
- Mini-511:
Input screen with App Id, Version Id
- Update loading on Display screen
https://jira.rakuten-it.com/jira/browse/MINI-511
> Input screen on Sample app

- .github/CODEOWNERS
This will allow all Code Owners to be default reviewers on all Pull Requests
> docs: Add CODEOWNERS file with team members

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplayTest.kt
1. Enable webview to support:
- Local Storage
- Session Storage
- IndexedDB
- Web SQL
- Cookies (default enabled)
Run successfully with webapp.
2. Add unit test and refactor  RealMiniAppDisplayTest
[MINI-524](https://jira.rakuten-it.com/jira/browse/MINI-524)
> feat: webview application storage

- .github/CODEOWNERS
remove donnie-jp from codeowners file
> remove donnie-jp from codeowners file

- build.gradle
> build: update gradle dependency version

- README.md
> docs: add MIT license badge to readme

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputActivity.kt
- testapp/src/main/res/values/strings.xml
Add UUID validation to the mini app id in InputActivity
MINI [814](https://jira.rakuten-it.com/jira/browse/MINI-814)
> refactor: validate the mini app id in input activity

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/base/BaseActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuBaseActivity.kt
- testapp/src/main/res/layout/app_settings_dialog.xml
Entering a bad guid should throw an error by calling api and should not make changes to the list. 
[MINI-820](https://jira.rakuten-it.com/jira/browse/MINI-820)
> fix: handling bad id from configuration

- miniapp/USERGUIDE.md
Fix examples in userguide to reflect the revised interface and add addtional examples for fetching list of mini apps and mini app info.
> docs: Update userguide samples

- miniapp/src/main/assets/bridge.js
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/res/values/colors.xml
- Update bridge js asset due to this [update](https://github.com/rakutentech/ios-miniapp/pull/63) from js sdk.
- Update color accent from ios.
- Generating uuid in sample app.
> update: add new bridge js, uuid for unique id in sample.

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/UUIDHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuBaseActivity.kt
--Sample App
Adding text observer when input `AppId`. 
[MINI-814](https://jira.rakuten-it.com/jira/browse/MINI-814)
> feature: input observer

- testapp/src/main/res/values/colors.xml
Change primary colors to be based on crimson red
> style: change primary colors to be based on crimson red

- miniapp/USERGUIDE.md
I will update the release date when it's decided.
> docs: Update readme and changelog for v1.1.0

- miniapp/USERGUIDE.md
Preparation for 1.1.1 release.
> docs: Update changelog and userguide for v1.1.1

- miniapp/USERGUIDE.md
This means we don't have to update the version name in the example every time we have a new release.
> docs: Change dependency example to use variable for version name

- testapp/build.gradle
Updates the user agent string to include the version information
NA
> Update the user agent string to include the version information

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfig.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfigSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplayTest.kt
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
Refactor some aspects of the naming related to the user agent implementation 
None
> refactor some aspects of the naming related to user agent implementation

- miniapp/USERGUIDE.md
Temporarily remove testbox document for release.
> doc: remove testbox config

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/adapter/MiniAppListAdapter.kt
Sample App:
Add missing code on miniapp list adapter. This will be affected when the testbox api is ready.
> fix: add missing code

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/WebViewDialog.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStatus.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplayTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStatusTest.kt
- Override js dialog event to not show URL.
- The action texts of the native dialog are shown as localized strings.
- Show miniapp display name in dialog title. This made the changes in source code:
Pass `MiniAppInfo` to webview. Remove `miniapp id`.
Save `MiniAppInfo` as json string in local.  Remove `version id` in storage.
[MINI-1228](https://jira.rakuten-it.com/jira/browse/MINI-1228)
> feature: webview custom dialog

- .github/CONTRIBUTING.md
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/OnSearchListener.kt
- testapp/src/main/res/layout/mini_app_list_fragment.xml
- testapp/src/main/res/menu/main.xml
- testapp/src/main/res/values/strings.xml
- testapp/src/main/res/values/styles.xml
- testapp/src/main/res/xml/searchable.xml
- Search for a mini app by title using search-box
- [MINI-1116](https://jira.rakuten-it.com/jira/browse/MINI-1116)
| Search icon on top  | Hint preview in the search box |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/66930373/87490851-adf7cb00-c681-11ea-9533-717e779b1dbd.png" alt="alt text" height="300"> | <img src="https://user-images.githubusercontent.com/66930373/87490872-b8b26000-c681-11ea-819e-1ae804ce6d5f.png" alt="alt text" height="300"> |
| Search result while miniapps found | Search result while miniapps not found |
| <img src="https://user-images.githubusercontent.com/66930373/87490889-c4058b80-c681-11ea-9a71-e2fbba8b6ad7.png" alt="alt text" height="300"> | <img src="https://user-images.githubusercontent.com/66930373/87490905-cf58b700-c6 …
> feature: add search box on top of miniapp list

- .github/CONTRIBUTING.md
Changelogs could be formatted by a convention. This PR aims to contribute a format.
> Add format for changelogs

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
There were two major issues reported after adding search feature. This PR will fix those issues:
* [MINI-1347](https://jira.rakuten-it.com/jira/browse/MINI-1347)
* Prevent showing "There is no Mini App found!" after settings saved
> Fix some issues

- .github/CONTRIBUTING.md
- CHANGELOG.md
- build.gradle
Also I realized that the contribution guide for the changelog was missing a type for changes to already existing features, so I've added the `Changed` type.
> Update min SDK to 23

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplayTest.kt
Clean deprecated methods.
[MINI-1239](https://jira.rakuten-it.com/jira/browse/MINI-1239)
> refactor: clean deprecation

- CHANGELOG.md
> docs: Update changelog for v2.0.0

- CHANGELOG.md
- miniapp/USERGUIDE.md
Preparation for 2.1.0 release.
> docs: Update changelog for v2.1.0

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ProfileSettingsActivity.kt
- testapp/src/main/res/layout/contacts_activity.xml
- testapp/src/main/res/layout/settings_menu_activity.xml
Two issues have been fixed by this PR on user details settings screen in sample app.
- `No contact available!` text was not showing because of a xml shape, it's fixed in this PR
- Photo can be picked from gallery by tapping on the photo
- Shrink margin at build info to look good
- MINI-955
> Fix issues in user details settings

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ProfileSettingsActivity.kt
Fix the issues to match the acceptance criteria defined by MINI-955
- Trailing whitespace is not allowed and should be automatically removed
- No field is explicitly required. 
- MINI-1744
- MINI-1745
> Fix issues related to user data settings ux

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ProfileSettingsActivity.kt
- testapp/src/main/res/values/strings.xml
After discussed with QA side, I have found to make this PR with the expected changes for user profile screen:
- Name field is optional 
- Save button can be enabled by default 
MINI-1757
> fix: name field is optional in profile screen

- CHANGELOG.md
Merging this to the `release/2.2.0` branch.
> docs: Update changelog for v2.2.0

- CHANGELOG.md
Merge changlog updates to master
> Merge 2.2.0 changelog into master

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/ads/AdMobDisplayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/ads/MiniAppAdDisplayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/ads/Reward.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/ads/AdMobDisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/ads/TestAdMobDisplayer.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- Display rewarded ads.
- Change in interstital ads: Not allow the same ads to be loaded when there is one still in progress.
- Update user guide of hostapp for AdMob integration.
MINI-1657
> feat: reward ads

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcherSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
We will aim to use `BridgeDispatcher` postfix convention to dispatch any action implementation from `MiniAppMessageBridge`.
> rename: UserInfoHandler to UserInfoBridgeDispatcher 

- CHANGELOG.md
Update changelog release date and add a couple missing items.
> docs: Update changelog for 2.3.0

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/adapter/MiniAppListAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/res/layout/item_footer_miniapp.xml
- testapp/src/main/res/layout/mini_app_display_activity.xml
- testapp/src/main/res/layout/mini_app_list_activity.xml
- testapp/src/main/res/layout/mini_app_list_fragment.xml
- testapp/src/main/res/layout/profile_settings_activity.xml
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/dimens.xml
- testapp/src/main/res/values/strings.xml
This PR will fix few issues related to search-box in sample app.
- Add a horizontal line as footer in miniapp list screen
- Disable "Pull to refresh" option while searching Mini App
- Search box should be reset after click on close button
- MINI-1348 
- MINI-1350
- MINI-1353
> Fix SearchBox issues in sample app

- codecov.yml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/AdBridgeDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/ScreenBridgeDispatcher.kt
Break down `MiniAppMessageBridge`. Move ad implementation into `AdBridgeDispatcher`.
Exclude non-test files in codecov.
> refactor: bridge ad delegation

- CHANGELOG.md
- codecov.yml
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/TokenData.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcherSpec.kt
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/AccessTokenActivity.kt
- testapp/src/main/res/layout/access_token_settings_activity.xml
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/strings.xml
Miniapp can get the access token from hostapp.
Able to provide the validation check between hostapp and miniapp based on miniapp id. HostApp can throw exception to reject the request of access token.
Note: As discussion, the user permission for access token will be implemented when first time permission is done.
MINI-1863
> feature: retrieve access token

- CHANGELOG.md
Merging this to the `release/2.4.0` branch.
> docs: Update changelog for v2.4.0

- CHANGELOG.md
> Merge 2.4.0 changelog updates to master

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
Update bridge js to have access token retrieaval feature.
> build: update bridge

- testapp/src/main/res/layout/settings_menu_activity.xml
Since the features has been increased in the settings screen in sample app, it's required to scroll the page specially for small screen size. This PR added a `ScrollView` to fix this issue.
> fix: support scrolling in sample app settings screen

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
Updated changelog and also added some additional information about throwing errors to a mini app.
> Update docs and changelog for v2.5.0

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
Merge 2.5.0 changelog to master
> Merge 2.5.0 changelog to master

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
- testapp/src/main/res/layout/settings_menu_activity.xml
Demo app:
Move the preview toggle below build info section.
Restore miniapp navigator.
MINI-1030
> sample: preview toggle

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/res/values/strings.xml
Search miniapp by id.
Hide loading mini app by id button when it's preview mode.
MINI-2176
> feat: search by id

- .github/CONTRIBUTING.md
- .github/pull_request_template.md
- README.md
Add Learning path and update PR template.
> docs: Add SDK Learning Path to contribution guide

- CHANGELOG.md
Merge the release of 2.6.0 to master.
> merge 2.6.0 changelog

- CHANGELOG.md
Release preparation for v.2.7.0.
MINI-2308.
> release: v2.7.0

- CHANGELOG.md
Merge release changlog of v2.7.0
> release: v2.7.0 (#228)

- miniapp/USERGUIDE.md
Added example for using in a Java project. Also added info that we don't specifically support usage of the SDK in Java.
> docs: Add Java example to user guide

- .circleci/config.yml
Publishes to the "Feature" group on App Center for branches matching `feature/*`.
> ci: Setup Demo App publishing from feature branches

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
Add the url query validation in setting of sample app.
MINI-2666
> sample: params validation

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplaySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- Change `UserInfoBridgeDispatcher` into interface.
- Remove application context in `RealMiniAppDisplayer` due to no usage.
> refactor: minor updates

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/CachedMiniAppVerifier.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/CachedMiniAppVerifierSpec.kt
Throw exception for SDK when cannot create or get crypto key.
MINI-2733
> exception: device keystore

- CHANGELOG.md
- build.gradle
- miniapp/USERGUIDE.md
- miniapp/build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/CachedMiniAppVerifier.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/CachedMiniAppVerifierSpec.kt
2.7.2 patch includes:
- Initialization time decrease
- Exception for miniapp verification into 
MINI-2843
> release: 2.7.2

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- README.md
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- miniapp/USERGUIDE.md
- miniapp/build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- testapp/build.gradle
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/WebViewActivity.kt
Also changed group id to io.github.rakutentech.miniapp and updated build config submodule.
MINI-2689
> build: Migrate publishing to Maven Central

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
Fix some issues that is reported in Android regression 3.0.0
- MINI-2941
- MINI-2942
> fix issues in sample app while regression of 3.0.0

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiCache.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCacheSpec.kt
There were missing unit test coverage while developing manifest feature, this PR aims to improve this coverage.
> add unit test coverage for manifest feature

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/Contact.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactAdapterPresenter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactInputDialog.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListAdapter.kt
- testapp/src/main/res/layout/contacts_activity.xml
- testapp/src/main/res/layout/dialog_add_contact.xml
- testapp/src/main/res/layout/item_list_contact.xml
- testapp/src/main/res/values/strings.xml
- Added name and email as optional to Contact.
- Display contact object in sample app.
- Input name & email for Contact in sample app.
- Change the contact dialog behavior: do not close dialog when there is error.
MINI-2910
> feat: add name & email to contact

- .github/CODEOWNERS
> Add gopi-karmakar to code owners

- CHANGELOG.md
Update missing v2.7.2 changelog.
> doc: v2.7.2 changelog

- miniapp/USERGUIDE.md
Added example showing how to deep link to mini apps.
MINI-2171
> docs: Add FAQ about how to deep link to mini apps

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/chat/ChatWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/res/layout/window_chat.xml
- testapp/src/main/res/values/strings.xml
This PR aims to fix some issues according to the following Links.
- MINI-3087
- MINI-3088
- MINI-3092
- MINI-3096
- MINI-3099
> bugfix: chat feature

- miniapp/USERGUIDE.md
Host Apps want to clear the session data of mini apps after a user logs out.
MINI-2606
> docs: Add FAQ for how to clear session data for mini apps/webviews

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppScheme.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/navigator/MiniAppExternalUrlLoader.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSchemeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/navigator/MiniAppExternalUrlLoaderSpec.kt
Support mail uri for miniapp and external webview.
MINI-1391
> feat: support mail uri

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/chat/ChatWindow.kt
- testapp/src/main/res/layout/window_chat.xml
Align with ios sample display.
MINI-3105
> fix: send message placeholder

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
Added operation on first time screen when pressing back button in sample app.
- MINI-3261
> add back button operation to first time screen

- testapp/src/main/res/layout/contacts_activity.xml
- testapp/src/main/res/values/dimens.xml
Added bottom padding in the contact list so the fab icon overlapping the delete action can work
MINI-3263
> added bottom padding in contact list recylerview

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppDownloadedListActivity.kt
Deleted app from Ras portal which is also removed from mini app list
MINI-2907
> add checking available miniapp  before showing downloaded minapp list

- testapp/build.gradle
Chnage dataBinding with buildFeatures as dataBinding is deprecated.
> update dataBinding to buildFeatures

- miniapp/proguard-rules.pro
Demo app is crashing as following [report](https://appcenter.ms/orgs/Rakuten-Early-Adoption-Organization/apps/Mini-App-Sample/crashes/errors/1630290296u/overview) with the build from https://github.com/rakutentech/android-miniapp/pull/305 
This PR aims to fix this issue 
a reference of the solution: https://issuetracker.google.com/issues/157983099?pli=1
> fix crash for crypto lib when minify enabled

- .circleci/config.yml
Fixing the file path issue for `mapping.txt` in circle config
> add post steps for mapping files

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridge.kt
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
- testapp/src/main/res/layout/qa_settings_activity.xml
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/strings.xml
Added QA option in AppSettings Menu page
MINI-3355
> Added UI to test AccessToken error type

- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/deeplink/SchemeActivity.kt
- testapp/src/main/res/values/strings.xml
Added deeplink support 
MINI-3289
> Added deeplink support

- CHANGELOG.md
Update change logs for `v3.4.0` build.
> update changelog for v3.4.0

- CHANGELOG.md
Update v3.4.0 release date to 2021-06-29
> update v3.4.0 release date

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooser.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooserDefaultSpec.kt
Webview can accept specific image file type.
MINI-3346
> Webview can accept specific file type

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/Points.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/PointsActivity.kt
- testapp/src/main/res/layout/points_activity.xml
This PR aims to prevent the `NumberFormatException` in demo app's `Points` settings for the values which is out of range.
- MINI-3470
> fix NumberFormatException with Int values in Points

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooser.kt
Able to upload multiple files at once.
MINI-3469
> [MINI-3469]Fix multiple file upload

- CHANGELOG.md
Update change logs for v3.5.0 build.
> Update changelog for v3.5.0

- CHANGELOG.md
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactAdapterPresenter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactInputDialog.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListAdapter.kt
User can edit contact name and email in contact list
MINI-2915
> MINI-2915 Editable contact list in app settings

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/res/layout/dialog_add_contact.xml
- testapp/src/main/res/values/strings.xml
This PR will add few enhancements for Contact ID, name and email adding in demo app e.g. 
- contact id, name and email inputs should not be empty
- refactoring random contacts generation with iOS-like values
- displaying a default random contact while adding a new contact
P/S: There is already an email validation, so it has been skipped.
- MINI-3325
> MINI-3325: demo app: enhancements for Contact ID, name and email inputs

- CHANGELOG.md
> Update changelog for 3.6.0

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/AndroidManifest.xml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/WebViewFileDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/navigator/MiniAppNavigator.kt
- miniapp/src/main/res/xml/miniapp_downloaded_file_provider_paths.xml
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/WebViewFileDownloaderSpec.kt
Merge the 3.6.0 candidate branch to master (including the feature for "File Download").
> Merge 3.6.0 candidate to master

- CHANGELOG.md
> Update changelog for 3.7.0 

- CHANGELOG.md
- Updated codebase with latest JS bridge
- Updated changelog for 3.8.0 (release date TBD)
> Update latest JS bridge 

- CHANGELOG.md
This PR aims to update the release date for `v3.8.0`.
> Update release date for 3.8.0

- CHANGELOG.md
Merge the 3.8.0 candidate branch to master.
> Merge 3.8.0 candidate to master

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
Soft input resize screen when keyboard hide views.
MINI-4292
> [MINI-4292] Fix soft keyboard resize screen

- CHANGELOG.md
- testapp/build.gradle
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/BuildVariant.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/strings.xml
Add a toggle switch to switch between prd and stg version.
https://user-images.githubusercontent.com/84305007/143395744-590ee19f-2854-452a-bce9-ce693a183305.mp4
MINI-4358
> [MINI-4358] Add toggle switch for prod

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/analytics/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtils.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionAdapter.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSchemeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtilsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppBridgeSpec.kt
Increase code coverage for better quality of code.
> Improve Code Coverage

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooser.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooserDefaultSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
Camera was not opening in real device, this PR aims to fix this issue.
- MINI-4473
> [MINI-4473] bugfix: image capture issue in real device

- testapp/src/main/res/layout/window_share_miniapp.xml
Remove center crop attribute from promotional image.
> Remove crop from promotional image

- CHANGELOG.md
This PR aims to update the release date for v3.9.0
> Update release date for 3.9.0

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppInfo.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppShareWindow.kt
- testapp/src/main/res/values/strings.xml
Merge the 3.9.0 candidate branch to master.
> Merge 3.9.0 candidate to master 

- CHANGELOG.md
This PR aims to update the release date for `v3.9.1`
> Update release date for v3.9.1 

- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
Code coverage improvement for better code quality
> Code coverage improvement

- CHANGELOG.md
Merge the 3.9.1 candidate branch to master.
> Merge 3.9.1 candidate to master

- build.gradle
This PR aims to update the scm version incrementer so that it can produce a major version e.g. `4.0.0`
> v4.0.0 / Update project version with major incrementer 

- CHANGELOG.md
This PR aims to update the release date for `v4.0.0`, also there are few more details has been added in the change-log.
> 4.0.0: Update release date

- CHANGELOG.md
- miniapp/USERGUIDE.md
Update the userguide, changelog and bridge.
[NO TICKET]
> [NO TICKET] Update changelog, userguide and bridge

- CHANGELOG.md
This fixes an issue with automatic versioning of the SDK. This must be merged using normal "Merge" and NOT "Squash and Merge"
> Merge 4.0.0 to master to fix versioning - DO NOT SQUASH

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloader.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
Handle the case if the host app cancel the file download by pressing the back button.
[NO TICKET]
> [NO TICKET] Download cancel by host app

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloader.kt
Added an initialization check before cancel.
[NO TICKET]
- [] I wrote/updated tests for new/changed code
> [NO TICKET] Fix appcenter crash 

- CHANGELOG.md
This PR aims to update the release date for v4.1.0
> Update release date for 4.1.0

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/analytics/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
- testapp/src/main/res/layout/qa_settings_activity.xml
- testapp/src/main/res/values/strings.xml
Added 2 Interfaces for `getMessagingUniqueId` and `getMauid` for MAUID V2.
MINI-4881
> [MINI-4881] Add Interface for MAUID V2

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
Display null if item is not available.
MINI-5008
> [MINI-5008] Display null if item is not available

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcherSpec.kt
After adding secure storage code coverage decreased a lot, this PR is for improving that situation. It is still not completed, We can improve more after we change the secure storage from file to database.
MINI-5031
> [MINI-5031] Improve test coverage

- miniapp/proguard-rules.pro
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/util/MiniAppDatabaseEncryptionUtil.kt
Fixes the crash regarding proguard for sqlcipher. 
NO TICKET
> [NO TICKET] Added proguard for sqlcipher

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
> [NO TICKET] Addressing the deleteItems issues reported by QA

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApi.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/MetadataApi.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/MetadataApiSpec.kt
Cherry pick from [MINI-5172](https://github.com/rakutentech/android-miniapp/pull/448/files) to release in 4.1.2.
> 4.1.2/cherry pick mini 5172

- build.gradle
This PR aims to fix the project version for `4.1.2` build in candidate using `incrementPatch`. However, we need to revert to `incrementMinor` again when we will finalize `4.2.0` build.
> 4.1.2 - Fix project version incrementer 

- build.gradle
This PR aims to fix the project version for 4.2.0 build using `incrementMinor`.
> Use incrementMinor to continue 4.2.0

- CHANGELOG.md
This PR aims to update changelog for v4.2.0 release e.g. date and missing feature.
> Update Change log for 4.2.0

- CHANGELOG.md
Merge 4.2.0 candidate branch to master.
> Merge 4.2.0 candidate to master

- .github/CODEOWNERS
> [NO TICKET] - Code owners update

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseImpl.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
This PR is addressing [MALI-1078](https://jira.rakuten-it.com/jira/browse/MALI-1078) and [MINI-5207](https://jira.rakuten-it.com/jira/browse/MINI-5207)
> [MINI-5285] Addressing the bulk data insert and storage limit issues raised by QA in MALI-1078 and MINI-5207.

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/MetadataApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCacheSpec.kt
Download manifest file again if language code changed.
MINI-5262
> Download manifest file again if language code changed

- CHANGELOG.md
This PR aims to add the necessary change logs for 4.3.0 version.
> Add change log for 4.3.0

- CHANGELOG.md
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
Merge 4.3.0 candidate branch to master.
> Merge 4.3.0 candidate to master

- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
This PR aims to update the correct metadata variable for maxStorageSizeLimitInMB in Demo app.
> [Debt] Update metadata variable for MaxStorageSizeLimitInMB 

- testapp/proguard-rules.pro
Beacuas of proguard rules, there is a crash in stg version.
NO TICKET
> [NO TICKET]Update proguard rules

- .github/CODEOWNERS
> [No Ticket]  Updated Team

- build.gradle
This PR aims to update the scm version incrementer so that it can produce a major version e.g. `5.0.0`.
NO TICKET
> [NO TICKET] Update project version with major incrementer

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewImpl.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
Fix crash in offline mode.
MINI-5639
> [MINI-5639] Fix crash in offline mode

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/Cache.kt
Including refactoring and handling tab switches when data is invalid.
[MINI-5538](https://jira.rakuten-it.com/jira/browse/MINI-5538)
> [MINI-5538] RAS credentials should persist when tab switched

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseImpl.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
> [MINI-5492] Adding More Unit Test Cases For Secure Storage

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
> [MINI-5638] Enabling The MiniAppID Text Field.

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiCache.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/analytics/rat_wrapper/CustomButtonViewWithArrow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/extensions/NavigationExtensions.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/FeaturesFragment.kt
- testapp/src/main/res/layout/custom_button_view_with_arrow.xml
- testapp/src/main/res/layout/features_fragment.xml
- testapp/src/main/res/values/attrs.xml.xml
- testapp/src/main/res/values/strings.xml
Back button will close the URL.
MINI-5633
> [MINI-5633] Back button Fix in URL

- build.gradle
Update the scm version to update the sdk version correctly.
NO TICKET
> [NO TICKET]Correct version update

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/deeplink/SchemeActivity.kt
Make list1 config primary for deeplink.
NO TICKET
> [NO TICKET] Make list1 config primary for deeplink.

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
> [MIN-5711] Clear storage should only delete all the records only and not the whole table itself.

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSize.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MiniAppSecureStorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
- testapp/build.gradle
Hotfix PR to fix https://jira.rakuten-it.com/jira/browse/MALI-1199 issue.
This PR changes is cherrypicked from 
* https://github.com/rakutentech/android-miniapp/pull/503/
* https://github.com/rakutentech/android-miniapp/pull/506/
* https://github.com/rakutentech/android-miniapp/pull/511/
* https://github.com/rakutentech/android-miniapp/pull/514/
[MALI-1199](https://jira.rakuten-it.com/jira/browse/MALI-1199)
> Hotfix changes for Android SDK v5.0.1

- README.md
Update repository readme to make it clearer for future newcomers that join us.
[MINI-5729](https://jira.rakuten-it.com/jira/browse/MINI-5729)
- [] I ran `./gradlew check` without errors
> [MINI-5729] Update Repository Readme

- build.gradle
This change needs to update the version 5.0.1.
NO TICKET
> [NO TICKET] Update the version incrementor for v5.0.1

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/util/MiniAppDatabaseEncryptionUtil.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/util/MiniAppDatabaseEncryptionUtilSpec.kt
> [MINI-5767] Fixing the NoSuchAlgorithmFound crash for Android 7 and below.

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/errors/MiniAppDownloadFileError.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/errors/MiniAppSecureStorageError.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/util/MiniAppDatabaseEncryptionUtil.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/analytics/MiniAppAnalyticsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtilsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/closealert/MiniAppCloseAlertInfoSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppFileDownloadDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/chat/ChatBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MiniAppSecureStorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/navigator/MiniAppExternalUrlLoaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStatusSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/util/MiniAppDatabaseEncryptionUtilSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandlerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewImplSpec.kt
This PR aims to improve branch code coverage. Please refer to the below comparison:
- MINI 4858
> [MINI 4858] Improve branch code coverage 

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/MiniAppPasswordTransformationMethod.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/DemoAppMainActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
- testapp/src/main/res/layout/settings_fragment.xml
This PR aims to provide a customized `PasswordTransformationMethod` class which helps to convert the given character sequence to a masked character e.g. '*'.  Please check the utility functions added in `AppHelper` in demo app for the usage.
- MINI-5839 (Demo in the Jira comment)
> [MINI-5839] Mask Project ID & Subscription Key in Settings in Demo App

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/analytics/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Obj.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/ActionTypeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
MiniApp can request host app to close itself.
MINI-5844
> [MINI-5844] Added miniapp close interface.

- testapp/src/main/AndroidManifest.xml
Added necessary tag to handle orientation change
MINI-5630
> [MINI-5630] Media handling orientation change

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/iap/MiniAppPurchaseItemListResponse.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/iap/MiniAppPurchaseRecord.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/iap/MiniAppPurchaseResponse.kt
Added necessary annotation to pass proguard check.
NO TICKET
> [NO TICKET] Added annotation for proguard check.

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/iap/InAppPurchaseBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/iap/InAppPurchaseBridgeDispatcherSpec.kt
Userguide testcase update for In-app purchase.
MINI-1734
> [MINI-1734] Userguide testcase update for IAP

- CHANGELOG.md
- admob-latest/build.gradle
- build.gradle
- in-app-purchase/build.gradle
> Merge candidate to master v5.3.0-alpha

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/analytics/MiniAppAnalytics.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/iap/InAppPurchaseBridgeDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandler.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewImpl.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/DemoAppMainActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/adapter/MiniAppListAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/viewModel/MiniAppListViewModel.kt
- testapp/src/main/res/menu/miniapp_list_option_menu.xml
- testapp/src/main/res/values/strings.xml
* Download MiniApp using the new interface
* Also, check if the Miniapp has been downloaded properly.
* Updated Demo app to test both the features.
Demo: https://rak.app.box.com/file/1291645410429
MINI-6259
> [MINI-6259] Added interfaces for background download

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
> [NO-TICKET] Avoid Removing manifest file.

- CHANGELOG.md
- build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/BundleMiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/BundleMiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppParameters.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandler.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/iap/InAppPurchaseBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandlerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
> [MINI-6314] Improve loading time for load miniapp from bundle

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppParameters.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandler.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandlerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
> [NO TICKET] Update miniapp intials by lazy

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridge.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/iap/InAppPurchaseBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
> [NO-TICKET] Add base64 encoding on Universal bridge dispatch

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
> [NO TICKET] Add generic base64
