rakutentech/android-miniapp

- .circleci/config.yml
The debug output displays some sensitive information in the logs on CI
> ci: Remove debug output for App Center upload

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/FileWriter.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppListerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/DownloadApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ListingApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtilsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/TestApi.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageTest.kt
Please note:
- At this time, the `create` takes in an object of type `MiniAppInfo` as version information is internal to SDK and the host app can not access it after receiving it from the response of the listing API.
- The module will most likely see changes and be converted into a state machine (right now it just makes use of legacy implementation), hence, the unit tests around `FileWriter` and some for Downloader is a TBD later
> base implementation for download & save of a mini app

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtils.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/FileWriter.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageTest.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListViewModel.kt
* implementation for displayer module
* integrate the sample app view model with the #create call + minor refactor
* migrate to parent and child file api for creating directories and writing downloaded files
* gson lenient
* Update webview display
Co-authored-by: Minh Nguyen (ミン） <60589925+minh-rakuten@users.noreply.github.com>
> base implementation for displayer module (#25)

- gradle/documentation.gradle
- miniapp/build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- build: Fix KDoc generation
- Dokka had some breaking changes in v0.10.0. We need to specify the path to the source files. They also changed skipEmptyPackages to false by default.
- docs: Exclude unnecessary classes from KDocs
> Fix KDoc generation

- miniapp/src/main/AndroidManifest.xml
It needs to be initialized before the Mini App SDK
Cherry-picking this fix from the `poc` branch.
> fix: Change init order of SdkUtils

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/legacy/core/utils/LocalUrlParser.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/legacy/download/utility/MiniAppFileWriter.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/legacy/download/work/worker/DownloadWorker.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/legacy/core/BaseTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/legacy/core/utils/LocalUrlParserTest.kt
This PR updates the implementation for `manifest` API endpoint. 
Since the structure is somewhat the same, and only the URL parsing scheme has changed, the legacy implementation has been updated.
All changes for updating endpoints implementation are being pushed to a separate branch at this moment (`update-impl-api-endpoints`). The adapted URL scheme lengthens up the URL in comparison to the previous one (as such the receiving end, SDK in this case, only requires content and the intelligence in URL for the directory structure in the current system implementation. This was discussed with BE team yesterday and has been taken up by them to see if there's some quick way to address it). IF they are able to find some quick fix for it, the implementation could again see some minor change.
In …
> feat: update implementation for new manifest endpoint

- miniapp/USERGUIDE.md
If the user puts a number such as 1 or 1.0 as the value for the host app version, then the app will crash
> docs: Add note in userguide about host app version

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerTest.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
Adds an alternative for the automatic clearing of WebView in the display unit for the usual lifecycle oriented scenarios.
[MINI-499](https://jira.rakuten-it.com/jira/browse/MINI-499)
> feat: auto clear up WebView resources for usual lifecycle scenarios

- miniapp/build.gradle
I noticed that the code coverage being reported didn't seem to be accurate, so I tried updating the Jacoco version. It seems that the older version was not ignoring some of the code generated by the Kotlin compiler.
> build: Update Jacoco to v0.8.5

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApi.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
The API specs have changed the `files` key to `manifest`.
> fix: Update ManifestApi response to match spec

- testapp/src/main/res/layout/mini_app_input_activity.xml
Updates the location of the display button on the input screen.
Though, I don't think it is a bug in any way, more of a UX suggestion rather (which is further opinionated). It is an overlaying tooltip after all. 
But just to be of consideration of suggestions, I have moved it to the other side.
[MINI-629](https://jira.rakuten-it.com/jira/browse/MINI-629)
> update the location of display button in input screen

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppInfoFetcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
Some error messages were getting swallowed because there was a redundant try catch in 'MiniAppInfoFetcher#getInfo'. The exceptions are already handled and wrapped as 'MiniAppSdkException' by the ApiClient, so there is no need to handle exceptions in the other class.
MINI-827
- [ x] I ran `./gradlew check` without errors
> fix: Ensure error messages from the server are passed along for 'MiniApp.create'

- miniapp/src/main/assets/bridge.js
Old version of bridge script had JS features which are unsupported in Android 5/6 webview.
MINI-923
> fix: Update bridge JS to support Android 5 and 6

- .circleci/config.yml
- miniapp/build.gradle
- miniapp/proguard-rules.pro
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppInfo.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- testapp/build.gradle
Add signing config for release build (the keystore is set as a base64 environment variable on CI), add prod settings, and publish release build to app center when releasing new versions of the SDK.
> Setup Prod release to App Center

- .circleci/config.yml
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/res/values/strings.xml
This is so all of the build types can be installed on a single device at one time. Also added the 'staging' build type so we can have a release build with staging settings.
Publish staging build to App Center instead of debug build. This is so QA will be testing the SDK in the same setting as it will be used by Users - in a release build minified with proguard
> Change app id and app name for each build type

- build.gradle
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplayTest.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListViewModel.kt
Base commit for showing the activity's context injection into the mini-app display.
Note: CI would fail at this moment because of code refactoring and breaking of unit tests.
Updated: 
- Retain `ApplicationContext` in `Displayer` to maintain compatability, will omit it in the next release.
- `getMiniAppView()` is labeled as deprecated function.
- Update test cases.
> base commit for activity's context injection into the mini app display

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStatus.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStatusTest.kt
- testapp/build.gradle
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuBaseActivity.kt
- Display build information in the setting menu. The build version is generated in `build.gradle` of testapp. There will the appending in apk build Version name`-build-$buildVersion`.
- From discussion & agreement, update sdk as loading miniapp with latest version. `IsLatestVersion()` is omitted.
[MINI-921](https://jira.rakuten-it.com/jira/browse/MINI-921)
> Feature/build_version_display & update_get_latest_miniapp

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewTest.kt
- testapp/build.gradle
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuBaseActivity.kt
- Fix custom scheme error redirection.
We had implemented the redirection with custom domain before by replacing custom scheme with http on `OnReceivedError`. However, in some webview versions, the behavior of displaying error is still there even the new redirection has been called. The solution is to stop display webview then wait after a while then finally calling redirection with http.
- Display sdk version sample app as a requirement from updated ticket.
[MINI-1118](https://jira.rakuten-it.com/jira/browse/MINI-1118)
[MINI-921](https://jira.rakuten-it.com/jira/browse/MINI-921)
> fix: stop display error page

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfig.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/AppInfoApi.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApi.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfigSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/AppInfoApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/adapter/MiniAppListAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/MiniAppListStore.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuBaseActivity.kt
- testapp/src/main/res/layout/app_settings_dialog.xml
- testapp/src/main/res/layout/item_list_miniapp.xml
- testapp/src/main/res/layout/item_section_miniapp.xml
- testapp/src/main/res/values/dimens.xml
- testapp/src/main/res/values/strings.xml
1/ Switching to test endpoint to see miniapp versions in Testing environment by adding Path on url:
MiniApp api: `.../test`
Manifest api: `.../test/manifest`
The data responses from server side are expected the same as they are now.
Update for the manifest configuration:
`IsTestMode`: Decide to run original api or testing one.
When this PR gets approved, require an update config on CI for this value:
- Staging
`IS_TEST_MODE`: true
- Production
`PROD_IS_TEST_MODE`: should be false. Production does not need testing miniapps.
2/ Update UI sample app
- Add toggle button to switch to Testing on Setting dialog.
- Display miniapp list as Section list. The section is miniapp name, items are miniapp versions & icons.
[MINI-235](https://jira.rakuten-it.com/jira/browse/MINI-235)
> Feature: testing endpoint

- build.gradle
Sometimes the snapshot version was not being set correctly for tags like 'v1.2.0-alpha2' when there was already an 'alpha' release. Set the snapshot suffix to match anything after the '-' in the tag. Also updated the axion plugin to the latest version
- x] I removed all sensitive data before every commit, including API endpoints and keys
> build: Fix version incrementer for snapshot versions

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/base/BaseActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
Sample app:
We had implemented the back navigation on webview, now we have the close button to quit miniapp.
[MINI-1097](https://jira.rakuten-it.com/jira/browse/MINI-1097)
> feature: close miniapp

- build.gradle
The SCM plugin is not able to read the tagged version
> hotfix: undo version plugin change

- .github/CONTRIBUTING.md
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/UUIDHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/res/color/text_enable_state.xml
A warning should appear while there are invalid inputs like the following cases:
- App host id is not UUID
- empty / blank characters 
For the UI, this PR aims to use `setError(CharSequence error)` from [TextView](https://developer.android.com/reference/android/widget/TextView).
- [MINI-1271](https://jira.rakuten-it.com/jira/browse/MINI-1271)
> fix: no invalid field warning in settings screen

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
To refactor the build info string by template in sample app settings screen.
> Refactor to a template for build info string in settings

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
Miniapps are not loading after saving the settings. Sample app has to relaunch to see the miniapps. This PR will fix the issue.
> Fix to load miniapps after save settings

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/UrlToFileInfoParser.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
Changes in the format of the URL returned in the manifest have broken our SDK because we depend on the `map-published` key in the URL. However, this key changed to `map-published-v2`.
Actually, it would be better to not depend on this key anymore. The reason it was depended upon is because we needed to know what path to save files into, however now that we have a ZIP file we no longer need that information. But this is just a quick fix for now to update the key.
MINI-1407
> fix: Update URL file parser to look for map-published-v2

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/FileWriter.kt
- When doing decompression, it's mandatory to create the intermediate directory container of the zip entry.
`JS-SDK-Sample` zip and other zips which have the same issue will load successfully from this fix. 
- This fix will also allow android sdk to extract the hidden folder.
> fix: create intermediate directory when unzip

- .circleci/config.yml
- README.md
- build.gradle
- miniapp/build.gradle
- testapp/build.gradle
Updated the CircleCI config to use our shared [CircleCI Orbs](https://github.com/rakutentech/android-buildconfig/blob/master/circleci/README.md).
Also updated the `config` submodule to the latest version and applied the config for publishing to github pages.
> Use shared Orbs in CircleCI config 

- .circleci/config.yml
It needs to be set after the project has been checkout out, so I've moved this step to the after-prepare-steps section
> ci: Fix error with setting release keystore

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
The MiniApp#create function was still using the old method (which has now been removed). Also removed the note about AppCompat because this was relevant to Android 22 and below only (we now support 23+).
> docs: Fix some issues in the user guide

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/UrlToFileInfoParser.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageTest.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/UrlToFileInfoParserTest.kt
Remove the dependency on the URL structure. No more need for getting file path.
[MINI-1408](https://jira.rakuten-it.com/jira/browse/MINI-1408)
> refactor: file path parse

- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/AppInfoApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/DownloadApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/MockWebServerBaseSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtilsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplaySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStatusSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/UrlToFileInfoParserSpec.kt
We can use one postfix as convention while titling the test files. I have found two types of postfixes e.g. "Test" & "Spec" are using in this repository, so we can use "Spec" in everywhere.
> Rename "Test" postfixes to "Spec"

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionManager.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplaySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionManagerSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/CustomPermissionPresenter.kt
- Include instruction to use custom permission feature in [USERGUIDE](https://github.com/rakutentech/android-miniapp/blob/master/miniapp/USERGUIDE.md).
- Refactor code to make `MiniAppCustomPermissionManager` internal. HostApp doesn't need to call `setCustomPermissions` unless revoking permissions.
> Add user-guide for custom permissions 

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionResponse.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionManagerSpec.kt
- build: Update JS bridge submodule
- This fixes an issue where the response was being returned to the user as as string rather than an object
- refactor: (Custom permissions) Rename 'isGranted' param to 'status'
-  This param doesn't represent a boolean - it represents a status of allowed, denied, or not available so it should be named accordingly.
- fix: JS objects weren't being sent correctly over JS bridge
- Objects were being sent with normal double quotes which causes problems because the keys/values in the object are surrounded by double quotes. So I have changed this to use backticks and also added a fix so that backticks will be escaped if included in the response value.
> JS Bridge updates for Custom Permission support

- .gitignore
We can uncomment `*.jks` and `*.keystore` in` .gitignore` to avoid accidental push of keystore files.
> Add keystore files in gitignore

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionResponse.kt
Added `@Keep` annotation to `MiniAppCustomPermissionResponse`. The JavaScript side relies on the key names of the response, so these shouldn't be obfuscated.
MINI-1715
> fix: Keep custom permission response from being obfuscated

- build.gradle
- miniapp/build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/CachedMiniAppVerifier.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/CachedMiniAppVerifierSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageSpec.kt
This is to prevent a cache poisining vulnerability. This works by saving an encrypted hash of the Mini App fils. If someone modifies the cached files for the Mini App (i.e. on a rooted device), then the hash verification will fail and the Mini App will be re-downloaded. It's also not possible for someone to modify the hash since it's encrypted - if they attempt to modify it then the decryption of the hash will fail.
I also needed to delete some unit tests related to SDK initialization - this is because the CachedMiniAppVerifier needs to use the AndroidKeyStore which isn't mocked by the test runner. However I think it's okay to not test the initialization code because part of it's purpose is to be the place where we can initialize things which aren't mockable.
MINI-1405
> feat: Verify cached mini app files using SHA-256 hash

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppScheme.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/CachedMiniAppVerifier.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplaySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
Default implementation of Share feature in `MiniAppMessageBridge`.
Passing `Activity` to `MiniAppMessageBridge` as optional parameter. `Activity` is mandatory to execute some methods.
MINI-1695
> refactor: default share implementation

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/UUIDHelper.kt
SDK:
Resolve phone scheme detection issue on Android 6 by replacing the current`shouldOverrideUrlLoading`. Have tested on other OS and found no problem as well.
Sample app:
Add UUID length check.
MINI-1614
MINI-1620
> refactor: android 23 compatibility

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppScheme.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/navigator/MiniAppExternalUrlLoader.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/navigator/MiniAppExternalUrlLoaderSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/component/SampleExternalWebView.kt
SDK: Allow open dialer in external webview.
Sample: `shouldOverrideUrlLoading` for android 6+.
MINI-1827
> refactor: external phone dialer

- miniapp/proguard-rules.pro
Fix problem: AdMob does not work on STG build with R8 enabled. The issue is for this [class](https://github.com/rakutentech/android-miniapp/blob/22f551246dd71451cf076fda459e263c6464f2e9/miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/ads/AdMob.kt#L19) check while running.
> fix: admob minified

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/ScreenBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
Remove fullscreen view when the hostapp has to clear miniapp view manually.
Update document about clearing miniapp.
> fix: clean fullscreen view

- codecov.yml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- Fix rotation in fullscreen
Our sdk already has the forced screen orientation feature. That feature applies to every case including fullscreen so I have removed redundant codes here. This solves the problem of fullscreen miniapp in hostapp with no orientation change handling.
- Fix HTML video fullscreen
I notice that when video goes fullscreen, our toolbar is visible (but cannot touch) so the flag `View.SYSTEM_UI_FLAG_LAYOUT_STABLE` is required. Then there is white space in position of status bar and navigation so I have to set the background of fullscreen view in black.
> fix: remove orientation request when fullscreen

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/adapter/MiniAppListAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/WebViewActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppDownloadedListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppPermissionSettingsActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppPermissionSettingsAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ProfileSettingsActivity.kt
- testapp/src/main/res/layout/contacts_activity.xml
- testapp/src/main/res/layout/mini_app_display_activity.xml
- testapp/src/main/res/layout/mini_app_input_activity.xml
- testapp/src/main/res/layout/miniapp_downloaded_list_activity.xml
- testapp/src/main/res/layout/profile_settings_activity.xml
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/dimens.xml
Recently, we have encountered one issue in sample app while importing the views which throws sometimes:
```
java.lang.IllegalStateException: swipeRefreshLayout must not be null
at com.rakuten.tech.mobile.testapp.ui.miniapplist.MiniAppListFragment$onStart$1.run(MiniAppListFragment.kt:71)
.....
```
This is happened because synthetic import of `swipeRefreshLayout` sometimes executes too early which can produce `NPE`.
We can solve this issue either using `swipeRefreshLayout?.` but it'll not execute the action we want when it's `null` at `onStart()`.
Another way is using a global reference i.e. `binding` for getting `swipeRefreshLayout`. I added the same solution in other views as well.
> fix: use binding as a reference for the views to import

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
Added MiniAppHasNoPublishedVersionException for the case when the mini app id exists on the server but the server has no published versions, and added MiniAppNotFoundException for the case that the server returns 404.
MINI-1971
> feat: Added exception types for some cases of server responses

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionWindow.kt
Previously, there was no support for back pressed when opening default permission UI. It should be the same operation while users press "Close" button. This PR added the fix for back button pressed.
- MINI-2033
> fix: support back pressed operation for default permission UI 

- testapp/src/main/res/layout/settings_menu_activity.xml
Following this [PR](https://github.com/rakutentech/android-miniapp/pull/191), fix the border line and put the scroll under toolbar because the toolbar should not be able to scroll up.
MINI-2102
> sample: scroll setting

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
Enable the miniapp to call media execution play/pause programmatically.
MINI-1973
> refactor: enable media play/pause programmatically

- CHANGELOG.md
- build.gradle
- miniapp/USERGUIDE.md
- miniapp/build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
Default implementation of handling external link.
The link will be opened in [Custom Tab](https://developers.google.com/web/android/custom-tabs). There is no support for returning data back to sdk native webview at the moment.
MINI-1697
> refactor: default external link handler

- CHANGELOG.md
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/component/SampleExternalWebView.kt
Turn on some setting flags on external webview to cover some errors.
Why: The hostapp is responsible for external webview implementation but we don't want our clients & partners see errors while testing in our demo app.
> sample: external webview update

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfig.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfigSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/MiniAppListStore.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/strings.xml
- Deprecated the "isTestMode" in `MiniAppSdkConfig`
- Added "isPreviewMode" support in `MiniAppSdkConfig`
- Change the API endpoint for "isPreviewMode" from "test" to "preview"
- Add "isPreviewMode" to user guide and changelog.
- Adopt Preview Mode in sample app. "Preview Mode" switch in sample app settings is visible now.
- MINI-2141
> api: support preview mode

- CHANGELOG.md
- README.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfig.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtils.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfigSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/AppInfoApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/strings.xml
- Added `MiniAppSdkConfig.rasProjectId`
- Deprecated `MiniAppSdkConfig.rasAppId`
- Use Project ID in sample app
- MINI-2039
> change: App ID configuration setting to use Project ID

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
In the last [preview mode pr](https://github.com/rakutentech/android-miniapp/pull/201), we were not passing value from `MiniappSdkInitializer` for `isPreviewMode` via secondary constructor of `MiniAppSdkConfig`.  So, if HostApp does have both `isPreviewMode` and `isTestMode` in their configuration, then SDK prioritizes `isTestMode` which is unexpected. This PR aims to fix this issue.
> make sdk initializer compatible for both isTestMode and isPreviewMode

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfig.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/AppInfoApi.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApi.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfigSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/AppInfoApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
There is no usage of hostapp version so this PR removes it in sdk and sample app.
MINI-2028
> api: remove hostapp version

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorage.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
Currently cannot load all versions of miniapp in preview mode. The cause is we made get miniapp by MiniAppInfo deprecated. This PR:
- Fix getting miniapp in preview
- Update miniapp cache in preview mode
- Change security validation of hashcheck. Using miniapp version id.
This fix is required to move MINI-235 into QA.
> refactor: get preview miniapp

- testapp/src/main/res/layout/item_list_miniapp.xml
- testapp/src/main/res/layout/item_section_miniapp.xml
Display app id in header and add version name in each item.
MINI-2174
> fix: miniapp item display with different version names

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
Refactor messages with specifying project id when `MiniAppNotFoundException` exception. 
MINI-2175
> refactor error messages with project id when `MiniAppNotFoundException` exception

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/component/SampleExternalWebView.kt
This PR adds a change for secondary webview in sample app, something like redirecting to default browser when there is `window.open` / `_blank` anchor href. Since, SDK has a default implementation for external url handling, so this change doesn't affect anything in sample app. But still we can test this PR by using `miniapp.create(appId, miniAppMessageBridge, miniAppNavigator)` inside `MiniAppDisplayViewModel`.
Note: There is a way to detect `window.open` distinctly in `WebChromeClient.onCreateWindow()`, but it's not reliable solution, so haven't included it.
- MINI-1928
> fix: redirecting to default browser when window.open anchor

- testapp/src/main/AndroidManifest.xml
Every time we open the app setting screen, the keyboard shows up and covers the permission section so users have to close keyboard to access permission.
This PR improves that UX.
> refactor: hide keyboard when start setting screen

- README.md
- miniapp/USERGUIDE.md
Sorry it looks like there are a lot of changes. Most of the content is still the same but was just rearranged. The only new content is the Mini App Features section which explains what each feature does. Also added a Table of Contents - this will be automatically generated by Jekyll when the documentation is published to Github Pages. Also put some of the longer code examples inside of expandable sections.
It's probably easier to preview it directly on my branch: 
https://github.com/corycaywood/android-miniapp/blob/docs/userguide-reformat/miniapp/USERGUIDE.md
MINI-1978
- [ x I have completed the [SDK Development Learning Path](../.github/CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
> docs: Reformat user guide into feature sections

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/Contact.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcherSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- Add `getContacts` feature to the mini app message bridge. This should just pass a list of IDs (each ID represents a contact).
- The "Contacts" setting was already implemented in the Demo App, so this needs to be hooked into the new `getContacts` feature.
- TODO: Implement `getContacts` in JavaScript bridge.
- MINI-2295
> feat get contacts

- CHANGELOG.md
- miniapp/src/main/res/values/strings.xml
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/res/values/strings.xml
- testapp/src/main/res/xml/searchable.xml
- Remove "app_name" resource from `miniapp/src/main/res/values/strings.xml`.
- MINI-2227
> move app name from sdk to hostapp

- testapp/src/main/AndroidManifest.xml
- testapp/src/main/res/xml/data_backup_rules.xml
`android:allowBackup="true"` is using for Google backup which can be seen in Google drive. Data of AppSettings is storing in Shared preferences which is [one of the files to backup](https://developer.android.com/guide/topics/data/autobackup.html#Files). There is might unexpected behavior when we change these settings in new releases of the Demo App. In this case, we can restrict the rule for Shared preferences not to do auto-backup in Google drive. This PR aims to bring a solution for this. 
However, I was checking [the document ](https://developer.android.com/guide/topics/data/autobackup#XMLSyntax)if there is something to specify the data from AppSettings, I think, they only support files/folders to exclude. 
```
<exclude> - Specifies a file or folder to exclude during backup. Here are …
```
> fix: disable google backup for shared preferences

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppHttpWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
Fix issue when location was showing during custom permission is denied but device permission is allowed. It seems that `onGeolocationPermissionsShowPrompt` has an intention to check permission state for `android.permission.ACCESS_FINE_LOCATION`, so we should add a barricade of custom permission while invoking the permission which affects Geolocation API. 
Initially, I intended to show dialogs for both device and custom permission before executing `GeolocationPermissions.Callback?.invoke(origin, true, false)`, but it seems the checkup of JS SDK is already enough. So, in Android side, I have used the value of custom permission under `onGeolocationPermissionsShowPrompt` at runtime.
- MINI-2314
> fix: retrieve location correctly in geo location flow

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
* In `UserInfoBridgeDispatcher.onGetContacts` PR, we haven't added the permission checkup for `MiniAppCustomPermissionType.CONTACT_LIST` like the user-name and profile photo we have. This PR aims to add the fix. 
* Add a common function e.g. `hasPermission` in `MiniAppCustomPermissionCache` for checking if any specific permission has been allowed or not.
> refactor: add permission checkup in onGetContacts in UserInfoBridgeDispatcher

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
Loading by url should not call `commonInit()` twice.
> fix: MiniAppHttpWebView init once

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/res/layout/contacts_activity.xml
- testapp/src/main/res/values/strings.xml
Previously, there was no ux acknowledgement when contacts are saved or not, this PR aims to improve this ux.
Business logic expectation: if no contacts saved, it will not show in sample miniapp. should be same experience like username / profile photo.
TBD
> ux debt: show text as notification when contacts are not saved 

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
Fix miniapp view init due to R8 obfuscation.
MINI-2445
- [] I wrote/updated tests for new/changed code
> fix: proguard check MiniAppWebView

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcherSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
Change `MiniAppMessageBridge.getProfilePhoto` and `MiniAppMessageBridge.getUserName` to use a callback so that the photo and name can be retrieved/generated asynchronously. Deprecate the old synchronous versions of these methods.
- MINI-2120
> feat: allow profile photo and user name to be retrieved asynchronously

- CHANGELOG.md
- build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- testapp/build.gradle
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/SampleApplication.kt
Add [appcenter crash reporting library](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android) to the demo app to diagnosis crash reports in appcenter. 
- MINI-2009
> feat: add crash reporting integration in demo app

- .circleci/config.yml
Deliver the apk from candidate branch.
Using the same staging apk. At first, I want to create the different config for candidate apk build but our CI job is running `./gradlew assemble` which execute all builds so I don't want many apk builds slow down the CI process. 
Note: After merging into `master` branch, `candidate` branch will follow. 
MINI-2246.
> build: ci job for candidate build

- .circleci/config.yml
There is [error](https://app.circleci.com/pipelines/github/rakutentech/android-miniapp/1252/workflows/32c9e203-bbaf-4f88-9c31-972c9a2d59e5/jobs/1479) when pipeline parameter contains space so I have created the distribution group `Release_Candidate`.
MINI-2247
> build: no space group

- CHANGELOG.md
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListViewModel.kt
Sample app:
Fix following the change from backend. The list is returned in created date order.
> fix: sample app - display wrong order group

- miniapp/USERGUIDE.md
- docs: Add note about admob not supported on Android 6
MINI-2207
> docs: Add note about admob not supported on Android 6

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/SampleApplication.kt
App-center crash reporting is enabled for all types of build before this PR, we can skip it for debug build.
> disable appcenter crash reporting when debug builds

- .circleci/config.yml
- CHANGELOG.md
- codecov.yml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/WebViewDialog.kt
Fix the problem cannot tap anything when close dialog by touching outside area.
Add cancel event listener to solve this problem.
Remove WebViewDialog out of test coverage when we don't support UI auto testing.
MINI-2597
> fix: dialog cancel event

- CHANGELOG.md
- build.gradle
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebViewClient.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
Set android 7 as minimum version for miniapp sdk.
Using the latest function `shouldOverrideUrlLoading`, no need to use deprecated function supported android 6 anymore.
MINI-2648
> build: minimum version 24

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/ads/AdMobDisplayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/ads/AdMobDisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- Remove ad unit id in map when ad loads failed -> user can able to call load ad again.
- Escape character for bridge post error.
MINI-2706
MINI-2707
> fix: ad map & post message error

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionWindowSpec.kt
There was an issue when a Mini App tried to call MiniApp.requestCustomPermissions twice in a row without waiting for the success/failure response of the previous call. This is because the CustomPermissionBridgeDispatcher can only be initialized with a single CallbackObj. There wasn't any reason for only a single CustomPermissionBridgeDispatcher object to be used, so I moved it's instantiation inline when the custom permissions request is made.
Also refactored CustomPermissionBridgeDispatcher a little to remove the initCallbackObj as it was no longer nescessary.
This fix can be tested with the following JS code:
```
window.MiniApp.default.requestCustomPermissions([ {name: window.MiniApp.CustomPermissionName.USER_NAME, description: 'test'} ]) …
```
> fix: Issue with simultaneous custom permission requests

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
Remove the prompt dialog for access token in a demo app to match ios.
QA raised ticket: MINI-2677
MINI-2866, 2867
> sample: remove prompt dialog for access token

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/Displayer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppHttpWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplaySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionWindowSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppViewModel.kt
- Ignore/filter to not request custom permissions if it is not mentioned in manifest in `CustomPermissionBridgeDispatcher`.
- MINI-2934
> allow mini app in the bridge to request only permissions that is defined in manifest

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppPermissionSettingsActivity.kt
- testapp/src/main/res/layout/list_custom_permission.xml
- testapp/src/main/res/values/strings.xml
Android is showing up all the permissions inside the demo app permission settings rather than the only one's present in Manifest. This is a fix belongs to SDK side, this PR aims to fix this issue. When there is no permission, the permissions settings screen in demo app will show a message about this emptiness. 
- MINI-2937
> fix: return permissions only included by manifest from custom permission cache while reading

- build.gradle
- miniapp/build.gradle
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppInfoFetcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/ads/AdMobDisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientRepositorySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtilsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/DisplayerSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplaySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooserDefaultSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/CustomPermissionBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionAdapterSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionWindowSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageSpec.kt
- Reduce the complexity of prepare permissions in `MiniAppCustomPermissionCache`.
- Using official kotlin mockito `org.mockito.kotlin:mockito-kotlin` which is based on what we're using `com.nhaarman.mockitokotlin2`.
> minor refactor

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapplist/MiniAppListFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppDownloadedListAdapter.kt
- testapp/src/main/res/layout/downloaded_item_list_miniapp.xml
- testapp/src/main/res/layout/item_list_miniapp.xml
- MiniApp list is showing full icon instead of cropping in a circle, this PR aims to adopt the same consistency in other places as well.
- The UX of item in both regular miniapp & downloaded miniapp list can be same.
> sample app: implement same icon style like miniapp list in other places

- testapp/src/main/res/drawable/bg_metadata.xml
- testapp/src/main/res/layout/window_preload_miniapp.xml
Manifests with long meta data were causing the permissions to not be viewable. This change moves the meta data into scroll view beneath the permissions
> fix: Demo App display of meta data

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
Implement request retries in the SDK for the `500` response code. The SDK should retry 5 times, with a backoff multiplier of 2. For example:
Initial Request --> failed --> wait 0.5 seconds --> First retry --> failed --> wait 1 second --> Second retry --> failed --> wait 2 seconds --> etc...
- MINI-1639
> network request retry on 500 response code

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooser.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileChooserDefaultSpec.kt
File path callback should be `null` after being used once. This PR aims to add this fix.
- MINI-3179
> Set `null` to file path callback 

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/res/layout/window_preload_miniapp.xml
- "Send Message" permission is not showing in demo app's preload screen, this PR aims to fix this ui in `window_preload_miniapp.xml `
- Sorry, I have merged MINI-3261 fix in master, so I have cherry-picked that commit for candidate branch.
- MINI-3264
> bugfix: preload screen scrolling 

- .github/CODEOWNERS
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/FileWriter.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppStorageSpec.kt
Check canonical path as google security suggestion.
In my perspective, we pass the path for a zip to be extracted so I don't think there is any real issue here. The only possibility is someone can do reverse engineering and modify android runtime execution.
MINI-3204
> refactor: check canonical path

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionWindowSpec.kt
SDK should encrypt the Mini App permissions before saving them to the cache.  Previously, custom permissions has been stored in a normal `SharedPreferences`, now we can migrate it to `EncryptedSharedPreferences`. This PR aims to fix this issue.
- MINI-1661
> encrypt the stored MiniApp custom permissions

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
Support loading new uploaded codebase by not saving storage in preview mode.
MINI-3120
> refactor: no save storage in preview mode

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/analytics/MiniAppAnalytics.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCache.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/verifier/StoreHashVerifier.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCacheSpec.kt
`DownloadedManifestCache.readFromCachedFile` should return `null` while manifest cached file is not found, this PR aims to fix this issue to prevent a crash.
- MINI-3371
> fix: return null when file is not found from downloaded manifest cache

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
- testapp/src/main/res/layout/qa_settings_activity.xml
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/strings.xml
- Prevent exception during calling `onError` asynchronously in `getUniqueId`.
- Add an error response for "getUniqueId" to the QA settings section in the demo app.
- MINI-3385
> fix: host app crashes when sending "onError" response for "getUniqueId"

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
Users can upload a new miniapp codebase using the same version id, in this case, previously it causes issues e.g.  MINI-3376 & MINI-3379.
This PR aims to fixes those issues while storing manifest into files.
- MINI-3376
- MINI-3379
> fix: preload screen re-launches after uploading new miniapp codebase by same version id

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCache.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/verifier/CachedMiniAppVerifier.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/verifier/MiniAppManifestVerifier.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/verifier/StoreHashVerifier.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/DownloadedManifestCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/verifier/StoreHashVerifierSpec.kt
Manifest verification has been added previously in https://github.com/rakutentech/android-miniapp/pull/305 where `MiniAppManifestVerifier` was introduced. After finishing of MINI-2945, this PR aims to refactor the verification process with manifest files. Mainly, `MiniAppManifestVerifier` will use the functions of `StoreHashVerifier` same like `CachedMiniAppVerifier`.
- MINI-2947
> [MINI-2947] improvement: migrate to file verification for manifest

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/Points.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppPermission.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionAdapter.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/PermissionsUtils.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/PointsActivity.kt
- testapp/src/main/res/layout/points_activity.xml
- testapp/src/main/res/layout/settings_menu_activity.xml
- testapp/src/main/res/values/strings.xml
- Add an interface to retrieve the user's points information with custom permission e.g. `rakuten.miniapp.user.POINTS`
- In the Demo App settings screen, add an option where the points data can be set.
- Update with JS bridge. 
- MINI-3240
> [MINI-3240] feat: user points implementation 

- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/errors/MiniAppPointsError.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/PointsActivity.kt
- testapp/src/main/res/layout/points_activity.xml
- testapp/src/main/res/values/strings.xml
Primary work of user's point interface has been added by https://github.com/rakutentech/android-miniapp/pull/331.
This PR aims to add `MiniAppPointsError` for sending it to the mini-apps.
- MINI-3240
> [MINI-3240] add user point error 

- miniapp/src/main/AndroidManifest.xml
Tel scheme link is not working in Android 11. Basically, `MiniAppScheme.openPhoneDialer` intent has no issue, but in `MiniAppScheme.startExportedActivity` while the `android.intent.action.DIAL` is trying to resolve the `packageManager` - it's getting blocked due to restriction in Android 11.  This PR aims to fix this issue by adding `<queries>...</queries>` element in manifest. 
reference: https://developer.android.com/training/package-visibility/declaring
- MINI-3524
> fix: Tel scheme url in Android 11

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/RealSignatureVerifier.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/SignatureVerifier.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/api/PublicKeyFetcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/verification/AesEncryptor.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/verification/PublicKeyCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RobolectricBaseSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/signatureverifier/RealSignatureVerifierSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/signatureverifier/SignatureVerifierSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/signatureverifier/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/signatureverifier/api/PublicKeyFetcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/signatureverifier/verification/AesEncryptorSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/signatureverifier/verification/PublicKeyCacheSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/signatureverifier/verification/TestKeyStore.kt
This PR is adopting [Signature Verifier SDK](https://github.com/rakutentech/android-signatureverifier) in MiniApp SDK.
- MINI-3418
> MINI-3418: Adopt Signature Verifier SDK in MiniApp SDK

- CHANGELOG.md
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadManifestPermission.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppPermissionAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/res/layout/item_list_manifest_permission.xml
- testapp/src/main/res/layout/window_preload_miniapp.xml
Added access token scopes requested for the RAE audience in first-time screen.
- MINI-3959
> [MINI-3959] Show the scopes requested for the RAE token in first time screen

- miniapp/USERGUIDE.md
- miniapp/src/main/AndroidManifest.xml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/WebViewFileDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/navigator/MiniAppNavigator.kt
- miniapp/src/main/res/xml/miniapp_downloaded_file_provider_paths.xml
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/WebViewFileDownloaderSpec.kt
Note that this is being merged to a `feature` branch because we will release this as it's own 3.6.0 release.
The mini app sdk receives a Base64 URI from the mini app which we save to a temporary file and then create an Intent to share the file to another App.
I added a few unit tests, but they don't really cover the feature fully, so probably I can make another PR to add more tests.
MINI-3999
> feat: [MINI-3999] Add support for downloading files from a mini app

- build.gradle
- miniapp/build.gradle
Jcenter has been deprecated and all of our depedendencies have been migrated elswhere
> Remove jcenter from build.gradle

- CHANGELOG.md
- miniapp/src/main/AndroidManifest.xml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/WebViewFileDownloader.kt
- miniapp/src/main/res/xml/miniapp_downloaded_file_provider_paths.xml
Created mini apps own implementation of FileProvider using the default implementation of FileProvider. This prevents manifest merger conflicts when the Host App is already using a FileProvider in their App.
MINI-4064
> fix: Create custom download cache file provider

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppDownloadedListActivity.kt
This PR will resolve the following issue when click on "Permissions" button in Demo app settings:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rakuten.tech.mobile.miniapp.testapp.debug/com.rakuten.tech.mobile.testapp.ui.permission.MiniAppDownloadedListActivity}: java.lang.RuntimeException: Cannot create an instance of class com.rakuten.tech.mobile.testapp.ui.miniapplist.MiniAppListViewModel
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
....
Caused by: java.lang.RuntimeException: Cannot create an instance of class com.rakuten.tech.mobile.testapp.ui.miniapplist.MiniAppListViewModel
at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewMode …
```
> bugfix: resolve crash when click on permissions button on settings page

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfig.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClientRepository.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtils.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientRepositorySpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtilsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
- testapp/build.gradle
- testapp/src/main/AndroidManifest.xml
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/deeplink/SchemeActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/error/QRErrorWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- Remove SSLPinningPublicKey from metadata.
- Add SSL pinning through `MiniAppSdkConfig`, if `sslPinningPublicKey` in `MiniAppSdkConfig` is not empty ssl pinning will be enabled.
- Update CHANGELOG and USERGUIDE
- Update the `ApiClientRepository` to store `apiClient` against `sdkConfig` instead of `sdkConfig.key`.
- Added  `sslPinningPublicKeyList` in `MiniAppSdkConfig` to be able to add backup public key.
> Add SSL pinning Only for QRCode Feature

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/SignatureVerifier.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/signatureverifier/api/PublicKeyFetcher.kt
There is an issue has been reported e.g. https://appcenter.ms/orgs/Rakuten-Early-Adoption-Organization/apps/Mini-App-Sample/crashes/errors/2398348339u/overview - when SignatureVerifier wants to fetch the public key from api using `PublicKeyFetcher`, its not working in non-debug builds because the `data class` has been minified. This PR aims to fix this issue. Additionally, there is an exception handling is preserved to return `false` value when verifying the signature in case there are other issues while preparing the `ECPublicKey`.
> Fix: kotlin.collections.ArraysKt__ArraysJVMKt.copyOfRangeToIndexCheck

- miniapp/USERGUIDE.md
SDK now supports API 28+ only.
> docs: Add note about deprecating support for Android 24 to 27

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostAppInfoHelper.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostEnvironmentInfo.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostAppInfoHelperSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostEnvironmentInfoBridgeSpec.kt
We need to support in SDK, so that, HostApp can provide locale value to MiniApp. A locale value is considered as a BCP 47 Language tag composed of 2 letters for the country and 2 letters for the language, separated by a dash e.g. `en-US`. In this purpose, this PR aims to add `hostLocale` field to `HostEnvironmentInfo`. 
- MINI-4415
> [MINI-4415] Get default locale from host app

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/res/values-ja/strings.xml
- miniapp/src/main/res/values/strings.xml
Host locale is coming empty when the device language is Chinese. This PR aims to fix it with matching with spec. By default, if HostApp doesn't support any language, then it should return `en-US` to MiniApp.
- MINI-4458
> [MINI-4458] bugfix: empty host locale value

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppInfo.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/analytics/MiniAppAnalyticsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/adapter/MiniAppListAdapter.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppShareWindow.kt
- testapp/src/main/res/drawable/ic_menu_share.xml
- testapp/src/main/res/layout/window_share_miniapp.xml
- testapp/src/main/res/menu/miniapp_display_menu.xml
- Extending MiniAppInfo by `promotionalImageUrl` and `promotionalText`
- Adding Sharing option to display the promotional content via `MiniAppDisplay`
https://user-images.githubusercontent.com/84305007/144957887-3af6be7b-c7a2-4b02-9415-ef0b4d4734e0.mov
MINI-4418
> [MINI-4418] Support promotional image text

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppViewModel.kt
This fixes a case where the the mini app is unable to be launched when the device is offline. The check being done on the manifest was failing when offline. We missed this case earlier because it only occurs when testing with multiple mini apps - we cache the manifest for the last launched mini app using ManifestApiCache
MINI-4635
> fix: Unable to launch mini app when device offline

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostEnvironmentInfo.kt
Previously we have to send all the version static info's to update locale, now only locale can be passed for updating.
MINI-4670
> [MINI-4670] Improve HostEnvironmentInfo to update locale

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
Addded some checks and try catch to fix some appcenter crash.
`java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity`
`IllegalArgumentException: SettingsMenuActivity - not attached to window manager`
`kotlin.TypeCastException: null cannot be cast to non-null type android.view.ViewGroup`
MINI-4754, MINI-4755, MINI-4756
> [MINI-4754][MINI-4755][MINI-4756] Fix some appcenter crash

- build.gradle
- miniapp/build.gradle
The older version of Dokka was not compatible with Kotlin 1.4.0+.
Also updated the android-buildconfig module.
MINI-4845
> build: Update dokka to 1.16.10

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/errors/MiniAppDownloadFileError.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloader.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloaderSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppBridgeSpec.kt
Added support for `data:` URIs to `MiniAppFileDownloader`.
MINI-4979
> feat: Add support for base64 data URIs to File Download

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/errors/MiniAppAccessTokenError.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/errors/MiniAppDownloadFileError.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/errors/MiniAppSecureStorageError.kt
Able to fetch null value for key's post clear storage from inside miniapp.
MINI-5007, MINI-5008,  MINI-5009
> [MINI-5008] Show null when get item failed After clear storage

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
Show Get Size 0 and Clear storage success on first launch.
MINI-5007
> [MINI-5007] Fix Size and Clear Storage Display on first launch

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppHttpWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebChromeClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebView.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/MiniAppWebviewSpec.kt
The secure storage loading is finishing before the JS injection has happened, so the load event was not able to be properly received by the mini app
> fix: Send secure storage load event after JS injection

- CHANGELOG.md
- build.gradle
- miniapp/USERGUIDE.md
- miniapp/build.gradle
- miniapp/src/main/AndroidManifest.xml
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtils.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitCreatorUtilsSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/RetrofitRequestExecutorSpec.kt
Remove the SDK dependency on `"io.github.rakutentech.sdkutils:sdk-utils"` from MiniApp SDK.
It's currently being used only to append some specific RAS headers to RAS requests. This PR aims to move those functionality directly into the Mini App SDK.
- MINI-5036
> [MINI-5036] Remove SDK Utils dependency from MiniApp SDK

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ManifestApi.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/MetadataApi.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ApiClientSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/ManifestApiSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/api/MetadataApiSpec.kt
if {testPath} value is a empty string then the get api became invalid because of `//` in the link, so seprate the api call for preview mode, {testPath} at the end is ok as it has no effect.
MINI-5172
> [MINI-5172] Separate API calls for preview mode

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDownloader.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkException.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/api/ApiClient.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppInputViewModel.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
- testapp/src/main/res/values/strings.xml
This PR aims to have the following changes:
- Return a specific error to the Host App for 429 status code e.g.`MiniAppTooManyRequestsError`
- If the provided Mini App ID is currently downloaded on the device, then the mini app files should be deleted.
- In Demo App: Display error message.
- MINI-4952
> [MINI 4952] Add support for HTTP error status 429 (Too many requests)

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/SettingsMenuActivity.kt
This PR aims to fix an UI issue in demo app's settings page when `MiniAppTooManyRequestsError` is being caught.
> [MINI-4952] Fix UI in Settings page for Too Many Requests Error

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
Close alert popup was missing when closing miniapp by back button press.
MINI-5276
> [MINI-5276] Added check before closing miniapp by back press

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppSdkConfig.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniappSdkInitializer.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
[MINI-5306](https://jira.rakuten-it.com/jira/browse/MINI-5306)
For Solution now multiplying with 1024 instead of 1000 to convert from MB to KB also changed the position of conversion now changing in one place only rather many places. It'll be a solution for Link Integration too.
…d the position of conversion now hanging in one rather many places. It'll affect for Link Integration too
> [MINI-5306] Discrepancy in limit set in QA settings and Maximum size displayed in Miniapp

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/res/values/strings.xml
This PR aims to add proper error message when empty name and email in contact list page in Demo app.
- MINI-4131
> [MINI-4131] Proper error message should be displayed when Contact Name and email are empty

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
This PR aims to fix an UI issue in QA Settings page.
- MINI-5361
> [MINI-5361] Save button of QA settings is not functional

- testapp/src/main/res/menu/settings_qa_menu.xml
- testapp/src/main/res/values/strings.xml
This PR aims to fix a crash when tap on bluetooth icon in QA settings screen.
- MINI-5362
> [MINI-5362] Settings: Tap on Bluetoth icon crashes app 

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandler.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewImpl.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
Previously miniapp was opening by only `miniapp id` , added another function to open open miniapp by `MiniAppInfo`.
MINI-5531
> [MINI-5531] Miniapp version fix

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSize.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MiniAppSecureStorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
- testapp/build.gradle
Cherry-Picking [fdc4f06](https://github.com/rakutentech/android-miniapp/pull/498/commits/fdc4f0628851f0e27c6d1c6a0aef9f00a61ed5d5) from candidate branch.
> [MINI-5641] Negative value displayed for available size if storage limit is set in decimal value

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
* When Mini App is launched, we should not create a DB by default unless the Secure Storage feature is used. This PR Aims to handle the flow of not creating the DB
[MINI-5711](https://jira.rakuten-it.com/jira/browse/MINI-5711)
> [MINI-5711] MiniApps that do not use secure storage should not have a DB created by default.

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/deeplink/SchemeActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppShareWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppListFragment.kt
Add onPause and onResume event on permission dialog and share dialog
[MINI-5696](https://jira.rakuten-it.com/jira/browse/MINI-5696)
https://rak.box.com/s/1pmxnhjlnc8heqi6mrm26ttmeuutoh82
> [MINI-5696] Missing events for open and close dialog

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
**Resolution:**
It was really a side effect of [MINI-5711](https://jira.rakuten-it.com/jira/browse/MINI-5711) and was a genuine issue. There are many cases to DB need to take care and since the DB load time was changed to insert time only from [MINI-5711](https://jira.rakuten-it.com/jira/browse/MINI-5711) so due to the previous flow a DB Unavailable check was causing the issue. However I already found the issue and fixed it and tested with many various scenarios and it seems to be working fine now as expected.
[MINI-5711](https://jira.rakuten-it.com/jira/browse/MINI-5711)
> [MINI-5733] Error while entering data once the MiniApp is closed and reopened.

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseImpl.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
It was a side effect of [MINI-5711](https://jira.rakuten-it.com/jira/browse/MINI-5711) and was a genuine issue. There are many cases to DB need to take care and since the DB load time was changed to insert time only from [MINI-5711](https://jira.rakuten-it.com/jira/browse/MINI-5711) so due to the previous flow DB was loaded and opened only once during MiniApp Launch time but now it's loaded and opened only during insert time, So because if that the DB was unavailable for the other functionalities. However I already found the issue and fixed it. Now the Db will be loaded and opened for other functionalities if the DB is available for a MiniApp in the device. Tested the fix with many various scenarios and it seems to be working fine now as expected. …
> [MINI-5737] Error on clear storage data once the MiniApp is closed and reopened.

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/AccessTokenActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ProfileSettingsActivity.kt
- testapp/src/main/res/layout/access_token_settings_activity.xml
- testapp/src/main/res/layout/mini_app_input_activity.xml
- testapp/src/main/res/layout/points_activity.xml
- testapp/src/main/res/layout/profile_settings_activity.xml
- testapp/src/main/res/layout/qa_settings_activity.xml
- testapp/src/main/res/layout/settings_fragment.xml
- testapp/src/main/res/values/dimens.xml
Usually, in Demo app we can clear input fields easily in several places by cross icon, but still there are some remaining fields to implement this UX. This PR aims to add the cross icon to clear input fields in those remaining input fields.
> [NO TICKET] Add cross icon to clear input fields in Demo app

- .github/workflows/candidate_to_master.yml
This PR aims to add Github-Action's workflow using [create-pull-request](https://github.com/marketplace/actions/create-pull-request) for opening a new pull request from candidate to master branch automatically after a successful release of MiniApp Android SDK. 
After creating a release tag in [here](https://github.com/rakutentech/android-miniapp/tags) we can store the latest release in https://github.com/rakutentech/android-miniapp/releases. It will trigger the Github Action workflow to create the pull request from candidate to master branch. The job-workflows can be tracked from https://github.com/rakutentech/android-miniapp/actions.
Todo: There should be a guideline how to use the process.
- MINI-4188
> [MINI-4188] Create "candidate to master" pull request automatically after a release done

- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/ui/MiniAppCustomPermissionAdapterSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
Remove the cache removing function to show the cached data properly.
MINI-5726
> [MINI-5726] Fix config data to show cached data

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
The fragment got destroyed and got the new MiniAppView instance instead, thus it gets different from the cached one. If it is loaded with the cached MiniAppView, it gets a different context attached to the activity. 
MINI-5755
> [MINI-5755] Invalidate Cached MiniAppView when Fragment got destroyed

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloader.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloaderSpec.kt
This PR aims to add a fix to prevent creation of zero byte-ed file when downloading a file by appending `Dot(.)' to the file name in Android 10. Basically, it's showing an issue as following:
```
java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/sample..csv
at com.android.providers.downloads.DownloadProvider.checkDownloadedFilePath(DownloadProvider.java:1091)
at com.android.providers.downloads.DownloadProvider.insert(DownloadProvider.java:719)
at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
at android.content.ContentResolver.insert(ContentResolver.java:1828)
......
at com.android.providers.downloads.DownloadStorageProvider.createDocument(DownloadStorageProvider.java:210)
at …
```
> [MINI-5796] Appending '.' to file names on file download creates a zero byte file in Android 10

- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/file/MiniAppFileDownloaderSpec.kt
This PR aims to fix an issue in MiniAppFileDownloaderSpec in master branch.
> [MINI-5796] quick fix: adopt variable name from MiniAppFileDownloaderSpec

- CHANGELOG.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/userinfo/Contact.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
Added `allEmailList` field to support multiple emails for contacts.
MINI-5815
> [MINI-5815] Support multiple emails in contacts

- testapp/src/main/res/layout/settings_fragment.xml
This PR aims to remove unused "Dynamic Deeplinks" button from settings page as it's moved to "General" page.
> [NO TICKET] Remove unused option from settings page

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactAddActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListAdapter.kt
- testapp/src/main/res/layout/activity_contact_add.xml
- testapp/src/main/res/layout/item_list_contact.xml
- testapp/src/main/res/layout/item_optional_email_address.xml
- testapp/src/main/res/values/strings.xml
Support multiple emails, including mandatory email, that would be 5 max.
Adding fields with Email Address(optional) placeholder text.
Validate the email address added in these text fields if it's not blank
If it's blank, the email address (optional) list wouldn't count.
[MINI-5828](https://jira.rakuten-it.com/jira/browse/MINI-5828)
https://rak.box.com/s/1lcz3fc53hb6zrl4kvt7f1zh8anmbwct
> [MINI-5828] Multiple optional emails demo app

- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCache.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/permission/MiniAppCustomPermissionCacheSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppPermissionAdapter.kt
Custom permission SHOULD NOT be sorted .
MINI-5859
> [MINI-5859] Remove sorting from saving custom permission

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
Error: Permission displayed twice because of faster clicks
Solution: Added delay after first click.
MINI-5883
> [MINI-5883] Disable double click on settings cog

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/DemoAppMainActivity.kt
Added condition on back button press when at top page. Application will be close if user is at the top page and press device's back button.
MINI-5882
> [MINI-5882] Fix back operation on top page

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniAppDisplay.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplay.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/display/RealMiniAppDisplaySpec.kt
Add sendJson public interface to send data to miniapp
MINI-5359
> [MINI-5953] Add sendJson public interface

- in-app-purchase/src/main/java/com/rakuten/tech/mobile/miniapp/iap/InAppPurchaseProviderDefault.kt
- in-app-purchase/src/main/java/com/rakuten/tech/mobile/miniapp/iap/MiniAppInAppPurchaseErrorType.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/MiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/RealMiniApp.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/iap/InAppPurchaseBridgeDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewHandler.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/RealMiniAppSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/AdBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/CustomPermissionBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/ShareContentBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/UniversalBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/chat/ChatBridgeDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostEnvironmentInfoBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/userinfo/UserInfoBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/view/MiniAppViewImplSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactAddActivity.kt
MiniApp was not loading if it uses the old architecture. This PR includes that fix.
MINI-6110
> [MINI-6110] Fix Miniapp loading issue

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/analytics/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostAppThemeColors.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/hostenvironment/HostThemeColor.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/BridgeCommon.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/UnimplementedMessageBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/MessageBridgeHelper.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/cache/Cache.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QASettingsActivity.kt
- testapp/src/main/res/layout/qa_settings_activity.xml
- testapp/src/main/res/values/strings.xml
Changes
- Added `MiniAppMessageBridge.getHostAppThemeColors` in MiniAppMessageBridge for retrieving primary and secondary theme color.
- Added qa settings to test primary and secondary color.
MINI-6077
> [MINI-6077] interface primary seconday color

- CHANGELOG.md
- miniapp/USERGUIDE.md
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/analytics/Type.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcher.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
- miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/Type.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/BridgeCommon.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MessageBridgeRatDispatcherSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridgeSpec.kt
- miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/UnimplementedMessageBridgeSpec.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/MessageBridgeHelper.kt
Added a new interface to send to dark mode status to miniapp to change the mode of the miniapp as well.
MINI-6131
> [MINI- 6131] Implement dark mode

- testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/FileUtils.kt
- testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/QAAnalyticsLogsActivity.kt
- testapp/src/main/res/menu/settings_qa_logs_menu.xml
- testapp/src/main/res/values/strings.xml
Add `Clear` button to clear analytic logs.
MINI-6206
> [MINI-6206] Add clear button on analytic log page
